#!/usr/bin/env bash
# Redirects error page to a specific site
apt-get -y upgrade
apt-get -y update
apt-get -y install nginx
echo 'Holberton School' | sudo tee /var/www/html/index.html > /dev/null
sed -i '/^sserver_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx start
