#!/usr/bin/env bash
# Allows port 80 to serve
sed -i 's/ ipv6only=on//g' /etc/nginx/sites-available/default 
sed -i 's/ 8080 / 80 /g' /etc/nginx/sites-enabled/default
sed -i 's/ ipv6only=on//g' /etc/nginx/sites-enabled/default 
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default 
sudo service nginx restart
