#!/usr/bin/env bash
# Displays Holberton School 10 times using while loop
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo bad luck
		((i++))
	elif [ $i -eq 7 ]
	then
		echo good luck
		((i++))
	else
		echo Holberton School
		((i++))
	fi
done
